// Encrypted token storage — Electron safeStorage (OS keychain-backed).
// Per ADR-002 and research/02-token-storage.md.
//
// Uses Electron's safeStorage API instead of @napi-rs/keyring because native bindings
// can't be bundled by esbuild in Obsidian plugin context. safeStorage ships with Electron,
// uses OS-native encryption (macOS Keychain, Windows DPAPI, Linux libsecret), no bundle cost.

import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type {
  StoredTokens,
  TokenStorageMethod,
  TokensMeta,
} from "@mc/shared";

const DATA_DIR = ".modular-context";
const TOKENS_FILENAME = "tokens.enc";
const META_FILENAME = "tokens.meta.json";
const GITIGNORE_FILENAME = ".gitignore";

export class EncryptionUnavailableError extends Error {
  constructor() {
    super(
      "OS-level encryption unavailable. On Linux, install libsecret and ensure a keyring daemon is running.",
    );
    this.name = "EncryptionUnavailableError";
  }
}

export class TamperedDataError extends Error {
  constructor() {
    super("Token file integrity check failed (decrypt returned empty or invalid)");
    this.name = "TamperedDataError";
  }
}

interface ElectronSafeStorage {
  isEncryptionAvailable(): boolean;
  encryptString(plainText: string): Buffer;
  decryptString(encrypted: Buffer): string;
}

function getSafeStorage(): ElectronSafeStorage {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const electron = require("electron");
  const store = (electron.safeStorage ?? electron.remote?.safeStorage) as
    | ElectronSafeStorage
    | undefined;
  if (!store) {
    throw new EncryptionUnavailableError();
  }
  return store;
}

export interface StorageOptions {
  /** Absolute path to the vault root (plugin passes from app.vault.adapter) */
  vaultRoot: string;
  /** Unique identifier per vault — used in meta.keyId for audit trail */
  vaultId: string;
}

export class SafeStorageMethod implements TokenStorageMethod {
  public readonly name = "keyring" as const; // reported as "keyring" — OS keychain backs safeStorage
  private readonly dataDir: string;
  private readonly tokensPath: string;
  private readonly metaPath: string;
  private readonly gitignorePath: string;
  private readonly vaultId: string;

  constructor(opts: StorageOptions) {
    this.dataDir = join(opts.vaultRoot, DATA_DIR);
    this.tokensPath = join(this.dataDir, TOKENS_FILENAME);
    this.metaPath = join(this.dataDir, META_FILENAME);
    this.gitignorePath = join(this.dataDir, GITIGNORE_FILENAME);
    this.vaultId = opts.vaultId;
  }

  async saveTokens(tokens: StoredTokens): Promise<void> {
    this.ensureDataDir();
    this.ensureGitignore();

    const storage = getSafeStorage();
    if (!storage.isEncryptionAvailable()) {
      throw new EncryptionUnavailableError();
    }

    const plaintext = JSON.stringify(tokens);
    const encrypted = storage.encryptString(plaintext);
    writeFileSync(this.tokensPath, encrypted, { mode: 0o600 });

    const meta: TokensMeta = {
      keyId: this.vaultId,
      algorithm: "aes-256-gcm",
      storageMethod: this.name,
      encryptedAt: new Date().toISOString(),
      schemaVersion: 1,
    };
    writeFileSync(this.metaPath, JSON.stringify(meta, null, 2), {
      encoding: "utf8",
      mode: 0o600,
    });
  }

  async loadTokens(): Promise<StoredTokens | null> {
    if (!existsSync(this.tokensPath) || !existsSync(this.metaPath)) {
      return null;
    }

    const storage = getSafeStorage();
    if (!storage.isEncryptionAvailable()) {
      throw new EncryptionUnavailableError();
    }

    const encrypted = readFileSync(this.tokensPath);
    let plaintext: string;
    try {
      plaintext = storage.decryptString(encrypted);
    } catch {
      throw new TamperedDataError();
    }
    if (!plaintext) {
      throw new TamperedDataError();
    }

    return JSON.parse(plaintext) as StoredTokens;
  }

  async clearTokens(): Promise<void> {
    if (existsSync(this.tokensPath)) {
      rmSync(this.tokensPath, { force: true });
    }
    if (existsSync(this.metaPath)) {
      rmSync(this.metaPath, { force: true });
    }
  }

  private ensureDataDir(): void {
    if (!existsSync(this.dataDir)) {
      mkdirSync(this.dataDir, { recursive: true, mode: 0o700 });
    }
  }

  private ensureGitignore(): void {
    if (existsSync(this.gitignorePath)) {
      return;
    }
    const content = [
      "# Auto-generated by modular-context — Google Workspace tokens",
      "# NEVER commit these files — they contain encrypted OAuth tokens",
      TOKENS_FILENAME,
      META_FILENAME,
      "",
    ].join("\n");
    writeFileSync(this.gitignorePath, content, { encoding: "utf8" });
  }
}

export function createStorageMethod(opts: StorageOptions): TokenStorageMethod {
  return new SafeStorageMethod(opts);
}
